import { forwardRef } from "react";
import type { Competition, ScoreSummary } from "../lib/types";
import { gradePoints } from "../lib/scoring";

const formatNumber = (value: number) => new Intl.NumberFormat("ja-JP").format(value);

const ScoreCard = forwardRef<HTMLDivElement, { competition: Competition; summary: ScoreSummary }>(({ competition, summary }, ref) => {
  return (
    <div
      ref={ref}
      className="rounded-3xl border border-mint-300/85 bg-mint-100 p-6 shadow-card"
      style={{ minWidth: "320px" }}
    >
      <div className="flex items-center justify-between">
        <div>
          <p className="text-xs uppercase tracking-[0.4em] text-ink-600">Nobocon Score</p>
          <h2 className="mt-1 font-display text-2xl text-ink-950">{competition.title}</h2>
          <p className="text-sm text-ink-600">{competition.eventDate || "日付未設定"}</p>
        </div>
        <div className="text-right">
          <p className="text-xs text-ink-600">合計ポイント</p>
          <p className="text-3xl font-bold text-ink-950">{formatNumber(summary.totalPoints)}</p>
          <p className="text-sm font-semibold text-ink-800">{summary.rank}</p>
        </div>
      </div>

      <div className="mt-4 grid grid-cols-2 gap-3">
        <div className="rounded-2xl bg-accent-500 px-3 py-2 text-night">
          <p className="text-xs">合計トライ</p>
          <p className="text-xl font-bold">{formatNumber(summary.totalTries)}</p>
        </div>
        <div className="rounded-2xl border border-mint-300 bg-mint-50 px-3 py-2">
          <p className="text-xs text-ink-600">1トライあたり</p>
          <p className="text-xl font-bold">{summary.pointsPerTry.toFixed(2)}</p>
        </div>
      </div>

      <div className="mt-4">
        <p className="text-sm font-semibold">完登課題</p>
        {summary.toppedProblems.length === 0 ? (
          <p className="mt-2 text-sm text-ink-600">完登はまだありません。</p>
        ) : (
          <div className="mt-2 space-y-2 text-sm">
            {summary.toppedProblems.map((problem) => (
              <div key={problem.id} className="flex items-center justify-between rounded-xl border border-mint-300 bg-mint-50 px-3 py-2">
                <div>
                  <p className="font-semibold">P{problem.label}</p>
                  <p className="text-xs text-ink-600">{problem.grade}</p>
                </div>
                <div className="text-right">
                  <p className="text-xs text-ink-600">獲得ポイント</p>
                  <p className="text-sm font-semibold">+{formatNumber(gradePoints[problem.grade])}pt</p>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      <div className="mt-4 text-xs text-ink-500">Generated by Nobocon Scorebook</div>
    </div>
  );
});

ScoreCard.displayName = "ScoreCard";

export default ScoreCard;
