import { forwardRef } from "react";
import type { Competition, ScoreSummary } from "../lib/types";
import { gradePoints } from "../lib/scoring";

const formatNumber = (value: number) => new Intl.NumberFormat("ja-JP").format(value);
const classLabel = {
  general: "一般",
  advance: "アドバンスクラス",
  master: "マスタークラス",
} as const;
const classHeadline = {
  advance: "4Q以下",
  master: "3Q以下",
} as const;

const ScoreCard = forwardRef<HTMLDivElement, { competition: Competition; summary: ScoreSummary }>(({ competition, summary }, ref) => {
  return (
    <div
      ref={ref}
      className="bg-mint-50 px-3 py-3 text-ink-900"
      style={{ minWidth: "320px" }}
    >
      <div className="border-b border-mint-300 pb-3">
        <p className="text-xs uppercase tracking-[0.4em] text-ink-600">Nobocon Score</p>
        <h2 className="mt-1 font-display text-2xl text-ink-950">{competition.title}</h2>
        <p className="text-sm text-ink-600">{competition.eventDate || "日付未設定"}</p>
        <div className="mt-3 grid grid-cols-2 gap-4">
          <div>
            <p className="text-xs text-ink-600">合計ポイント</p>
            <p className="text-3xl font-bold text-ink-950">{formatNumber(summary.totalPoints)}</p>
          </div>
          <div className="text-right">
            <p className="text-xs text-ink-600">獲得ランク</p>
            <p className="text-3xl font-bold text-ink-950">{summary.rank}</p>
          </div>
        </div>
      </div>

      <div className="mt-4 grid grid-cols-2 gap-4 border-b border-mint-300 pb-3">
        <div>
          <p className="text-xs text-ink-600">合計トライ</p>
          <p className="text-xl font-bold text-ink-950">{formatNumber(summary.totalTries)}</p>
        </div>
        <div className="text-right">
          <p className="text-xs text-ink-600">1トライあたり</p>
          <p className="text-xl font-bold text-ink-950">{summary.pointsPerTry.toFixed(2)}</p>
        </div>
      </div>

      <div className="mt-4">
        <p className="text-sm font-semibold text-ink-900">完登課題</p>
        {competition.participationClass !== "general" && summary.autoTopPointsTotal > 0 && (
          <p className="mt-2 border-l-4 border-accent-500 bg-accent-100/40 px-3 py-2 text-xs text-ink-700">
            {classLabel[competition.participationClass]}参加のため、
            {classHeadline[competition.participationClass]}全完扱いの
            {formatNumber(summary.autoTopPointsTotal)}ptを加点済み
          </p>
        )}
        {summary.toppedProblems.length === 0 ? (
          <p className="mt-2 text-sm text-ink-600">完登はまだありません。</p>
        ) : (
          <div className="mt-2 space-y-2 text-sm">
            {summary.toppedProblems.map((problem) => (
              <div key={problem.id} className="flex items-center justify-between border-b border-mint-300 py-2">
                <div>
                  <p className="font-semibold">
                    <span className="text-moss-600">{problem.grade}</span> - {problem.label}
                  </p>
                </div>
                <div className="text-right">
                  <p className="text-xs text-ink-600">獲得ポイント</p>
                  <p className="text-sm font-semibold">+{formatNumber(gradePoints[problem.grade])}pt</p>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      <div className="pt-2 text-xs text-ink-500">Generated by Nobocon Scorebook</div>
    </div>
  );
});

ScoreCard.displayName = "ScoreCard";

export default ScoreCard;
